name: ScreenAgent
options:
  bundleIdPrefix: com.screenagent
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  ScreenAgent:
    type: application
    platform: macOS
    sources:
      - path: ScreenAgent
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.screenagent.app
        INFOPLIST_FILE: ScreenAgent/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: ScreenAgent/ScreenAgent.entitlements
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_NAME: ScreenAgent
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: ScreenAgent/ScreenAgent.entitlements
